### PR TITLE
Update cython wrapper

### PR DESCRIPTION
**Pull request by lukashergt**
This is an attempt at making the wrapper work again. This currently only works for `python<3.12`.

### CODE REVIEW

**Comment by aryan-t22** [comment]
Works!

**Comment by lukashergt** [comment]
I made some changes to the Makefile to handle more python versions. Would be great if you could give it a fresh test run, @aryan-t22 .

**Comment by aryan-t22** [comment]
> I made some changes to the Makefile to handle more python versions. Would be great if you could give it a fresh test run, @aryan-t22 .

Sure, will do right after the meeting!

**Review by aryan-t22 — COMMENTED** [review]
Just did a test run and it works fine!

**Comment by lukashergt** [comment]
> Just did a test run and it works fine!

Thanks @aryan-t22, if you are happy with the changes please approve the PR and then I'll squash and merge it to the master branch.

**Review by aryan-t22 — APPROVED** [review]

**Pull request merged**
